### ISSUE TITLE
Dep Socities

### ISSUE THREAD

**Issue by keerthanpg** [thescholarsavenue/societytable#1]
Department societies as a second series? eg Mekanika, Bitwise, Archi wala, and the teams behind pruthvi, samudra manthan, agri fest, etc
Also, you left out Code Club, and if Cognitio is not a society, you can add it there. I think theyre a start up, not sure.

**Comment by iashris** [comment]
Code Club was precisely left out because it is limited to the CSE Department. Since most students know about their respective departments' society and the others are inaccessible to them, adding them would have served no purpose (if the purpose is to make the first years aware of stuff they could do) But of course, for pure documentation purpose, it could be done.

**Comment by mankeyboy** [comment]
There is also the newer Tech Societies like Swarm and ARK which have been
working since the past year that are missing. We could probably put the
extended 10 societies in a new line and then do an extension for all the
dept societies.
